remote_theme: pmarsceill/just-the-docs
title: "Open Robo"
description: A free robo advisor for all
heading_anchors: true
url: "https://henrydavidge.github.io/open-robo"
plugins:
  - "jekyll-remote-theme"
